### ISSUE TITLE
won't stream

### ISSUE THREAD

**Issue by cirrusUK** [ItzBlitz98/torrentflix#11]
is it possible to edit the script to use mpv or mplayer ad default player ?

**Comment by ItzBlitz98** [comment]
Did you figure out what the problem was ?

**Comment by cirrusUK** [comment]
i did thanks, i didnt have vlc installed (mpv) i tried to run it w/o changing config to mpv, all good now, thanks for this awesome tool.

**Comment by ItzBlitz98** [comment]
Nice glad you got it working, And no problem :+1:
