### ISSUE TITLE
Way to search programmatically?

### ISSUE THREAD

**Issue by leshow** [ItzBlitz98/torrentflix#15]
Is there a way to use this module programmatically to search for torrents and save the magnet/torrent info for later use?

for example something like

```
var tflix = require('torrentflix');

tflix.search('search terms', function(err, results){
console.log(results):
});
```

I would like to use your torrent search scrapers for searching many torrents and storing it for later, not necessarily just for streaming video right after a search.

**Comment by ItzBlitz98** [comment]
Unfortunately no this isn't built to be a module. 

Not sure if this is what you wanted but you probably could modify the spawn command to do something else like launch an actual torrent client if you strip out the peerflix arguments.

**Comment by ItzBlitz98** [comment]
Will close this if you have any other questions feel free to post them here.

**Comment by leshow** [comment]
I actually do have one question, I've forked your library because there is no other decent node modules which have good torrent site search result scrapers, I plan to execute the torrent searches in a loop and save the resulting torrent files after the user has selected them (I'm pulling data on music releases and want to allow the user to select a tracker, then select a torrent for each release; the search terms are created dynamically, however).

I noticed however that when the prompt/inquirer code is put in a loop, node's execution doesn't halt on the response... but rather it continues pushing the prompt question after question to the console without waiting for user input.

Do you have a recommendation for how I can have the inquirer actually wait for user input, so that each prompt can be executed sequentially in some kind of dynamically created loop?

**Comment by ItzBlitz98** [comment]
Yea i ran into the same problem when building this, Its because node works asynchronously.

There are a few ways around this there is a module called async you can use and wait for a callback  before running the next task you want to do:

https://github.com/caolan/async#seriestasks-callback

So for example you can do [task] [task] [task] [prompt]

I'm also using promises for the actual scraping. http://howtonode.org/promises.
Once i have grabbed everything from the torrent site i send a promise response with an object of all the data that the main script is waiting for and then handles.

If you need a guide or a basic how two i'm happy to write one up for you.

**Comment by leshow** [comment]
This is great, thanks for pointing me in the right direction. Let you know
how it goes.

On 7 May 2015 at 10:16, Declan notifications@github.com wrote:

> Yea i ran into the same problem when building this, Its because node works
> asynchronously.
> 
> There are a few ways around this there is a module called async you can
> use and wait for a callback before running the next task you want to do:
> 
> https://github.com/caolan/async#seriestasks-callback
> 
> So for example you can do [task] [task] [task] [prompt]
> 
> I'm also using promises for the actual scraping.
> http://howtonode.org/promises.
> Once i have grabbed everything from the torrent site i send a promise
> response with an object of all the data that the main script is waiting for
> and then handles.
> 
> If you need a guide or a basic how two i'm happy to write one up for you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ItzBlitz98/torrentflix/issues/15#issuecomment-99882570
> .

## 

Evan Cameron
