### ISSUE TITLE
question: redundancy in onResolve in main.js

### ISSUE THREAD

**Issue by leshow** [ItzBlitz98/torrentflix#18]
It seems like the callback for the various torrent searches have a lot of copy-pasted code, I'm referring to all of the `xxxxSearch` methods in main.js

specifically this part:

```
        for (var torrent in data) {
          var date_added, title;
          var number = data[torrent].torrent_num;
          //var title = data[torrent].title;
          var size = data[torrent].size;
          var seed = data[torrent].seeds;
          var leech = data[torrent].leechs;

          if(history == "true"){
            var found = searchHistory(data[torrent].title);
            if(found){
               title = chalk.red(data[torrent].title);
             } else {
               title = chalk.yellow(data[torrent].title);
             }
          } else {
            title = chalk.yellow(data[torrent].title);
          }

          console.log(
            chalk.magenta(number) + chalk.magenta('\) ') + title + (' ') + chalk.blue(size) + (' ') + chalk.green(seed) + (' ') + chalk.red(leech)
          );
        }
```

is there any reason why this code isn't moved into it's own function to reduce the LOC in that file and the redundancy there? I see some small differences but nothing that couldn't be handled and still let us abstract the code elsewhere. 

Before I make this change I wanted to get your thoughts. Is there any specific reason you've written it this way?

**Comment by ItzBlitz98** [comment]
Honestly no there wasn't a valid reason for doing this other than me never expecting this to get as popular as it did.

If you wish to improve it feel free i would really appreciate it.

**Comment by leshow** [comment]
Sounds good! I'll have a PR for ya within a few days :+1:

**Comment by leshow** [comment]
PR [#19](https://github.com/ItzBlitz98/torrentflix/pull/19)
