### ISSUE TITLE
VLC prevents window switching

### ISSUE THREAD

**Issue by capoderra** [ItzBlitz98/torrentflix#20]
Arch + Gnome 3. Cannot switch windows once VLC is playing the show (VLC is always in the foreground). When in full-screen, cannot leave full-screen until the show ends. Window switching is prevented either way. Cannot switch windows using Alt+Tab or the super key. Super key shows overview of Activities, but clicking on any window other than VLC will bring VLC to the front again. Once VLC is closed, window switch resumes as normal.

**Comment by ItzBlitz98** [comment]
Huh i built this using arch + gnome 3 but i don't use vlc i use mpv.

As far as the bug report goes peerflix handles player launching but this seems like strange behaviour are there no settings on vlc like always stay on top ?

**Comment by capoderra** [comment]
I installed mpv... same behavior. So it's not vlc. Any ideas?

**Comment by walidsa3d** [comment]
Peerflix keeps the player window on top by default.

**Comment by ItzBlitz98** [comment]
Yea i think Caspian hit the nail on the head (thanks for chiming in :))

If you run:

```
torrentflix --config="gedit"
```

Find:

```
"peerflix_player_args": "",

```

add --not-on-top in the quotes so it looks like this:

```
"peerflix_player_args": "--not-on-top",
```

That should hopefully fix your problem, I wasn't sure if vlc did that as well i thought only mpv did.

**Comment by capoderra** [comment]
Worked! Thanks so much!

**Comment by ItzBlitz98** [comment]
Great will close this now then :+1:
