### ISSUE TITLE
Streaming torrent problem on Windows (EDITED)

### ISSUE THREAD

**Issue by ghost** [ItzBlitz98/torrentflix#22]
On Windows 8.1 I can't stream with Torrentflix using npm 2.14.4 with nodejs 4.1.2

I used these instructions from Github page until I selected one of these torrents I've wanted to watch

And then I get stuck on this message from the torrent I opened:

Streaming Revolution OS (2001) - 20-year history of GNU, Linux, open source, and the free software movement 

It doesn't grab the torrent to stream it and doesn't show the seeders and peers from cmd for some reason regardless the configuration I've tried...

Is this a bug? Because on Linux especially on Ubuntu based distros like Linux Mint 17.x I never had that problem!

Bear in mind that Peerflix did not make any problems as Torrentflix.

Thanks in Advance!

**Comment by ItzBlitz98** [comment]
Hey sorry about the long reply been really busy as of late.

I will look into this windows support was added by someone a while ago but a few things have changed since then maybe something broke along the way. Will see what i can find.

**Comment by ghost** [comment]
Thanks for the reply and take your time to take a look into it! I appreciate your effort and your insistence for this program! :+1:

**Comment by cdelaserna** [comment]
I have the same exact issue. I am using windows 10 and node 4.2.1.

**Comment by chdagenais** [comment]
look like the streaming is still happening. If you select the torrent, wiat a while, then open vlc and open http://localhost:8888  you get your stream. Only thing missing is no feedback from peerflix in the CLI

**Comment by ItzBlitz98** [comment]
Sorry it took me this long to look into the issue.

This should now be fixed for anyone still interested could you please test and let me know ?

**Comment by ghost** [comment]
Thank you @ItzBlitz98 for fixing that issue! Sorry for being late to respond to this! I downgraded to Windows 7 SP1 and I downloaded the latest version of Nodejs v5.4.0 with npm 3.5.3 (at this time of writing) and it works as expected!

Thank you for taking this effort to fix that issue once again! :)

Michael
