### ISSUE TITLE
An index of the file to stream.

### ISSUE THREAD

**Issue by godDLL** [ItzBlitz98/torrentflix#23]
My version of `peerflix` exits after initial "peers" screen with all zeroes. Doesn't matter if I try it myself from BASH command-line, or from the `torrentflix` CLI.

But if I give it an `-l` and select the file I want to stream all seems to work OK.

```
-i, --index     changed streamed file (index)                
-l, --list      list available files with corresponding index
```

Is this something that changed in `peerflix`, or just my specific torrent?

**Comment by walidsa3d** [comment]
I think you should ask peerflix developers.

**Comment by ItzBlitz98** [comment]
Yea this sounds like something you should be reporting to the peerflix devs.

**Comment by godDLL** [comment]
Suppose I should.

I see at least three issues on their side, that all look very similar to mine, or at least rooted in the same-y causes.

mafintosh/peerflix/issues/224
mafintosh/peerflix/issues/193
mafintosh/peerflix/issues/189

**Comment by ItzBlitz98** [comment]
Will close this issue as its not to do with Torrentflix.
