### ISSUE TITLE
Feature req: Select search engine on command line

### ISSUE THREAD

**Issue by ComedyTomedy** [ItzBlitz98/torrentflix#24]
Hello, excellent work! As a useful bonus, torrentflix circumvents my ISP's firewall (UK), so I use it for all my torrent searches, streaming or otherwise.

As the title says, I'd like an option to select the search site from the CLI. Perhaps like this:

```
-e, --engine [name] Site to use for searching. Use --list-engines for possible values.
--list-engines      List valid names for --engine 
```

Examples:

```
$ torrentflix -s ebook -e kickass
$ torrentflix -s "movie title" -e tpb
```

(Hmm, if there were also a `-n 1` to select the first match, torrentflix could be used entirely non-interactively)

---

Update: I'm now implementing this, but it would be nice if there were a way to go from `tpb` to The Pirate Bay.

**Comment by aamnah** [comment]
any update on your implementation?

**Comment by ItzBlitz98** [comment]
Fixed in https://github.com/ItzBlitz98/torrentflix/commit/9fdb95a7b35fcd6b31c99e8e2b918db977720cba
