### ISSUE TITLE
[ENHANCEMENT] Chromecast support

### ISSUE THREAD

**Issue by pechitook** [ItzBlitz98/torrentflix#28]
First off, amazing project. Thank you for this :)

I'd like to know if you are considering working on the Chromecast support for torrentflix. Is it in the roadmap?

I've been doing some research and [chromecast-player](https://www.npmjs.com/package/chromecast-player) seems to be a nice starting point. Also [peercast](https://github.com/mafintosh/peercast) and [castnow](https://github.com/xat/castnow) might be easier to integrate, depending on how you want to integrate this into torrentflix.

If you do are interested in developing this, what do you think is the best way to integrate it?

Thanks!

**Comment by pechitook** [comment]
Actually, by just installing [castnow](https://github.com/xat/castnow) and modifying this value in torrentflix's config `"peerflix_command": "castnow"` it works as expected, subtitles and everything :)

**Comment by ItzBlitz98** [comment]
Glad you got it working, Been meaning to get myself a chromecast.

Will close this is you find any issues i'll be happy to sort them out :+1:

**Comment by BlitzKraft** [comment]
Is there is a way to provide a commandline argument, to set player to chromecast when needed and use local player by default?
