### ISSUE TITLE
torrentflix crashs

### ISSUE THREAD

**Issue by monst6** [ItzBlitz98/torrentflix#29]
Crashes in docker "Dockerfile"

FROM ubuntu:14.04.3
RUN apt-get update
RUN apt-get -y install vim git curl wget python
# RUN curl -sL https://deb.nodesource.com/setup_0.10 | sudo -E bash - #NODE 0.10

RUN curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash - #NODE 4
# RUN curl -sL https://deb.nodesource.com/setup_0.12 | sudo -E bash - #NODE 1.12
# RUN curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash - #NODE 5

RUN apt-get -y install nodejs
# RUN npm install webtorrent -g

RUN npm install -g peerflix
RUN npm install -g torrentflix
CMD torrentflix

**Comment by ItzBlitz98** [comment]
This is a pretty unique use case. Does it throw back any errors of any kind ? I'm not really sure what i'm looking at.

**Comment by monst6** [comment]
Issue was torrentflix was passing --vlc to peerflix. I was running CLI on ubuntu without VLC.
