### ISSUE TITLE
Custom Config Location

### ISSUE THREAD

**Issue by gld1982ltd** [ItzBlitz98/torrentflix#3]
`torrentflix --config="nano"` opens an empty file `~/.node/lib/config.js`. This file is not loaded by torrentflix. The default config is used every time.

I have `prefix = ~/.node` in my .npmrc

**Comment by ItzBlitz98** [comment]
This is interesting thanks for the report.

I have pushed a commit using a different method of working out where torrentflix is, If you could test it that would be greatly appreciated.

I'll also get working on a way to change the config location.

**Comment by gld1982ltd** [comment]
The config file is loading correctly now. I tested on both a local and global installation.

**Comment by gld1982ltd** [comment]
You can have torrentflix check for it's config (maybe  ~/.torrentflix.js or something similar) and if it exists open it for editing. If ~/.torrentflix.js does not exist, then torrentflix can copy it's default config to ~/.torrentflix.js and open it for editing. This way, you can have the default config ready to fall back on if you mess up the custom config.

**Comment by ItzBlitz98** [comment]
Awesome thanks for testing.

That's a pretty great suggestion will try to find time to implement it. Thanks.
