### ISSUE TITLE
Rarbg integration update

### ISSUE THREAD

**Issue by rarbg** [ItzBlitz98/torrentflix#34]
Hello
Please upgrade your app to utilize the available api of our site instead of direct hitting it.
You can read the api docs here
https://torrentapi.org/apidocs_v2.txt

**Comment by ItzBlitz98** [comment]
Fixed d1870377febc9a329ab8e3af016a0a8520d03578

Wasn't aware there was an api, Thanks for the heads up :+1:

**Comment by rarbg** [comment]
Thanks @ItzBlitz98
