### ISSUE TITLE
Question: Can i set default torrent site for search?

### ISSUE THREAD

**Issue by aamnah** [ItzBlitz98/torrentflix#37]
I pretty much always use the same site for search, have to select the same thing every time. Is it possible to set a default search site? Or can it be passed as an argument?

**Comment by walidsa3d** [comment]
Check https://github.com/ItzBlitz98/torrentflix/issues/24 , same issue

**Comment by ItzBlitz98** [comment]
Fixed in https://github.com/ItzBlitz98/torrentflix/commit/9fdb95a7b35fcd6b31c99e8e2b918db977720cba
