### ISSUE TITLE
The Pirate Bay

### ISSUE THREAD

**Issue by walidsa3d** [ItzBlitz98/torrentflix#4]
Please add support to https://thepiratebay.se/ since it is back online. Thanks.

**Comment by ItzBlitz98** [comment]
I was actually about to add the piratebay but when i last looked it was being flooded with fake torrents.

Has that been resolved ?

**Comment by walidsa3d** [comment]
They're still there, I hope they remove them soon

**Comment by ItzBlitz98** [comment]
Ok well decided to add this in but did what i did with the kickass scraper and pulled the users rank as well. Keep an eye on those skulls and you should be fine :+1: .

**Comment by walidsa3d** [comment]
Thank you
