### ISSUE TITLE
Peerflix won't start after upgrading dependencies

### ISSUE THREAD

**Issue by chdagenais** [ItzBlitz98/torrentflix#41]
https://www.diffchecker.com/nkkpxky9

After an upgrade of peerflix dependencies, peerflix won't start/shows. torrent isn't downloaded 

Edit: it's since 0.31.0 , when read-torrent was replaced by parse-torrent . All working fine with peerflix@0.30.0

**Comment by ItzBlitz98** [comment]
I think this is a issue you should bring up with peerflix we just pass arguments to it.
