### ISSUE TITLE
Torrent project don't provide all functionality #48

### ISSUE THREAD

**Issue by ahivert** [ItzBlitz98/torrentflix#50]
Torrent project source don't provide all the functionality the others have.
- limit the number of response
- set the base url in config file (permit to change the url without wait an update)
- cat argument (even if not use for now)

**Comment by ItzBlitz98** [comment]
I also don't like that the scraper is an external project, Means that we have to wait for them to fix upstream  if anything breaks. I would prefer scrapers to be baked in so we can fix them quicker if they break.
