### ISSUE TITLE
Arrow key selection for torrent site not working

### ISSUE THREAD

**Issue by joojie** [ItzBlitz98/torrentflix#52]
the arrows aren't working for selecting torrent site in git shell windows 10
cursor moves (invisibly) up and down without moving >
when enter is pressed YTS is selected
after search and selection an invalid "torrent identifier" error crash occurs when torrent begins to play(?)

**Comment by ahivert** [comment]
Is it working on the default 'cmd' of Windows ?

**Comment by joojie** [comment]
Yes it's working on the default 'cmd' of windows. All steps work
successfully however: After playback completes (vlc launched/ selected
torrent streamed) last function loops in command window endlessly and all
control within window is lost requiring the window to be closed externally.
Great job keep it up hope this helps.
