### ISSUE TITLE
How would I?

### ISSUE THREAD

**Issue by yukaputz** [ItzBlitz98/torrentflix#54]
How would I used this to just get the .torrent file so I can pass it to client?

**Comment by ahivert** [comment]
torrentflix --help give you all parameters accepted.

If you want open a file with your client please use -o like "open"

**Comment by yukaputz** [comment]
Thankyou for you response.  I apologize if this all seems elementary.  I'm still new to this os.  So I'm running a *_headless *_media server, the intention is to be able to quickly ssh to my server, run torrentflix and pass the torrent file to rtorrent which is bound to a vpn.  Since there is no x enviroment how would I pass it to rtorrent via xdg?   sudo torrentflix -xdg-open ????

**Comment by leshow** [comment]
torrentflix -o will pass the torrent to xdg-open, i've added this feature quite a while ago
