### ISSUE TITLE
results not coming

### ISSUE THREAD

**Issue by flik** [ItzBlitz98/torrentflix#55]
Kickass has results but In command line search nothing is coming. why ?

**Comment by leshow** [comment]
scraper probably needs to be updated

**Comment by ahivert** [comment]
Please give us more information :
- What do you have typed ?
- What is your OS ?
- Have you an error or just nothing ?

I've just test a Kickass search through the cli with 'spider man' and I obtained some results.

**Comment by flik** [comment]
ubuntu. and I am searching torrent

**Comment by ItzBlitz98** [comment]
Are you using the current kat domain in your config?
