### ISSUE TITLE
Encryption?

### ISSUE THREAD

**Issue by dbakathaillist** [ItzBlitz98/torrentflix#56]
Hello,

Is there a way to configure torrentflix to work with a proxy server? For instance, I have a subscription to BTGuard, which uses private servers to encrypt my downloaded torrent traffic so my ISP doesn't see. Its been working very well for me and I'd like to continue using it with this if possible.

**Comment by ItzBlitz98** [comment]
Its always a good idea to set your network up to use a vpn rather than relying on the app to do it.
