### ISSUE TITLE
Print magnet link to console

### ISSUE THREAD

**Issue by relaytheurgency** [ItzBlitz98/torrentflix#58]
I would like to have an option to print the magnet link/torrent file. I don't have a convenient way to set a default torrent application or anything like that. I will try to get a pull request together but if it would be a quick fix for you that would be awesome (I don't know node/javascript)

**Comment by ItzBlitz98** [comment]
What os are you using ? 
If you are using linux / mac i think just putting echo in the peerflix_command section will print out the magnet plus some other stuff.

**Comment by relaytheurgency** [comment]
Right now I've commented out the opn call in main.js and added a console.out(torrent) which is working. For some reason I can't get xdg-open to cooperate with deluge-console.

**Comment by ItzBlitz98** [comment]
I think xdg is mostly for gui apps, I have just taken a look and it seems you cant pass a command line argument to deluge-console to load a torrent. You know torrentflix has the ability to download a torrent rather than stream it as well using peerflix?

**Comment by relaytheurgency** [comment]
You can with `deluge-console add`, I do it with pirate-get which has an option to pass the torrent to whichever program you'd like (but limited to tpb :(). I'll look into peerflix bit also might submit a PR to give an option to pass the magnet link to whichever program the user likes.
