### ISSUE TITLE
Torrentflix close after select torrents, does not streaming

### ISSUE THREAD

**Issue by LoboTormenta** [ItzBlitz98/torrentflix#59]
Hello, guys, I love torrenflix

Recently i did a fresh install on fedora 23 and i install nodejs and npm then i did the procedure of install peerflix and torrenflix has usual (npm install -g ) but torrenflix does not start streaming, it close after select the torrent, so i love torrenflix and reformat my pc and i did a fresh install of linux mint 17.3 but i have the same problem, i hope you can help me, because i spend the last 3 day searching a solution, even i tried different versions of nodejs trough nvm and persist the problem.

My very best regards.

**Comment by ItzBlitz98** [comment]
Thanks for the kind words, I have pushed out a new release as i haven't done one in sometime. Please test and see if your problem persists.

**Comment by LoboTormenta** [comment]
Oh mate, I haven't lucky, it close after start download, I did some changes to config, and I discover if I switch vlc to totem, torrenflix doesn't close, and never start totem for streaming, if I switch to vlc, ,suddenly close, I had enable subtitles for Spanish. and vlc for streaming player.

I appreciate your help and thank you very much for you attention.

**Comment by paulodiovani** [comment]
@ItzBlitz98 There's no new release at https://github.com/ItzBlitz98/torrentflix/releases

I need a tag/release to update [AUR Package](https://aur.archlinux.org/packages/torrentflix/)

**Comment by ItzBlitz98** [comment]
@paulodiovani Apologies i have published a new release.

@bigardo Turns out this is not an issue with torrentflix its with peerflix.

There is an open issue here https://github.com/mafintosh/peerflix/issues/274 and a PR to fix this issue https://github.com/mafintosh/peerflix/pull/275 So it hopefully should be working again soon just update peerflix when a new release is tagged.

**Comment by paulodiovani** [comment]
Thanks, @ItzBlitz98. I've just subscribed to that issue and PR. 
I think we could hold this and #60 until they are fixed, to prevento someone else to reopen the issue.

**Comment by ItzBlitz98** [comment]
I'm fine with that a workaround for now would be to just downgrade peerflix:
`npm -g install peerflix@0.33.0`

**Comment by LoboTormenta** [comment]
Hello

Thanks all of you, for me, the bug is fixed, just open app.js on peerflix module and edit the line 84 and add another parentesis just like [https://github.com/mafintosh/peerflix/pull/275/ i have the latest version of peerflix and so loved torrentflix.

Best Regards. @ItzBlitz98 very very good job
