### ISSUE TITLE
Subtitles not working

### ISSUE THREAD

**Issue by paulodiovani** [ItzBlitz98/torrentflix#60]
When I set `"use_subtitle": "true"` on `config`, video is not downloaded or started (tested with _Brazillian Portuguese_).

Recorded bug:
 [![asciicast](https://asciinema.org/a/48141.png)](https://asciinema.org/a/48141)

**Comment by ItzBlitz98** [comment]
https://github.com/ItzBlitz98/torrentflix/issues/59#issuecomment-224467043 as i think this is related.
