### ISSUE TITLE
failing identifying the torrent files

### ISSUE THREAD

**Issue by je-vv** [ItzBlitz98/torrentflix#64]
% torrentflix 
? What torrent site do you want to search? YTS
? Search for a torrent:  before i wake
Searching for before i wake on YTS...
1) Before I Wake (2016) 720p 712.38 MB 1418 617
2) Before I Wake (2016) 1080p 1.47 GB 1136 478
? Torrent to stream (eg. 1, 2, 3..) or (b)ack or (e)xit:  1
Streaming Before I Wake (2016) 720p
/usr/local/lib/node_modules/torrentflix/lib/torrent_parse.js:20
        if(typeof torrent.files !== undefined){
                         ^

TypeError: Cannot read property 'files' of undefined
    at /usr/local/lib/node_modules/torrentflix/lib/torrent_parse.js:20:26
    at /usr/local/lib/node_modules/torrentflix/node_modules/read-torrent/index.js:18:13
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Please notice that peerflix (including subtitles) works OK with:

peerflix "magnet:?xt=urn:btih:409FE3B892B5B546E5058A205ECC7460F68711C6&dn=Before+I+Wake+%282016%29+%5B720p%5D+%5BYTS.AG%5D&tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fp4p.arenabg.ch%3A1337&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337" -t download/Before\ I\ Wake\ 2016\ 1080p-720p\ BluRay\ x264-[YTS\ AG]\ [All\ Releases].srt -k -- --fs

So, not sure why torrentflix fails...  I tried it with mpv or vlc players, and them with or without subtitles enabled...  Seems like torrentflix can't handle torrents, or files in torrents?

**Comment by je-vv** [comment]
Just in case using the release latest version, 9.0.0.  Installed from aur (arch).  Thx!

**Comment by nirvana7777** [comment]
Yes im facing this same issue. help pls ! thank you ;)

**Comment by ItzBlitz98** [comment]
This was fixed in a commit but i cant remember which
