### ISSUE TITLE
Issue searching torrent on Cpasbien.io

### ISSUE THREAD

**Issue by kalimeroo** [ItzBlitz98/torrentflix#75]
Hi,

When running a search on with cpasbien engine, it always return the torrents that are displayed on the homepage of cpasbien.io.

**Comment by ahivert** [comment]
The search on cpasbien.io (wich is redirected to cpasbien.cm) seems broken
no ?

**Comment by kalimeroo** [comment]
I just checked and indeed the search on cpasbien.cm is broken. It's then not an issue with torrentflix, sorry.
