### ISSUE TITLE
Doesn't update using npm

### ISSUE THREAD

**Issue by BobbieGoede** [ItzBlitz98/torrentflix#77]
Running torrentflix always tells me there is a new version of torrentflix and I can update using npm install -g torrentflix, this installs the same version (9.0.0) and running after installing the new version  gives me the same instructions for updating.

**Comment by pychi** [comment]
get the same error

**Comment by paulodiovani** [comment]
There is a `9.0.1` release not yet submited to `npm`

- https://github.com/ItzBlitz98/torrentflix/releases
- https://www.npmjs.com/package/torrentflix

**Comment by BobbieGoede** [comment]
Thanks, I didn't realize updating manually was such a small task so I'm up to date now. Not sure why 9.0.1 hasn't yet been submitted to npm though.

**Comment by ItzBlitz98** [comment]
Apologies it took some time all is fixed now.
