### ISSUE TITLE
Airplay not working

### ISSUE THREAD

**Issue by 25hash** [ItzBlitz98/torrentflix#8]
i'm trying to play something via airplay but it's always streaming to VLC.

here's my config :

/\* what player you want peerflix to use */
var peerflix_player = "--airplay";

and if i try to load a torrent or magnet it's always trying to stream to vlc.

**Comment by ItzBlitz98** [comment]
Looking into this now, Quick question though as i don't own an airplay device. 

Can you pass subtitles to it from peerflix ?

Edit: Did a search and you have an open issue with peerflix about subtitles not working won't pass them till this is fixed.
