### ISSUE TITLE
Could not locate the bindings files.

### ISSUE THREAD

**Issue by bigodel** [ItzBlitz98/torrentflix#83]
I installed torrentflix via npm on a Void Linux machine, and I simply doesn't work. Every time I try to launch it I get this error message:

```
/usr/lib/node_modules/torrentflix/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/torrentflix/node_modules/node-expat/build/node_expat.node
 → /usr/lib/node_modules/torrentflix/node_modules/node-expat/build/Debug/node_expat.node
 → /usr/lib/node_modules/torrentflix/node_modules/node-expat/build/Release/node_expat.node
 → /usr/lib/node_modules/torrentflix/node_modules/node-expat/out/Debug/node_expat.node
 → /usr/lib/node_modules/torrentflix/node_modules/node-expat/Debug/node_expat.node
 → /usr/lib/node_modules/torrentflix/node_modules/node-expat/out/Release/node_expat.node
 → /usr/lib/node_modules/torrentflix/node_modules/node-expat/Release/node_expat.node
 → /usr/lib/node_modules/torrentflix/node_modules/node-expat/build/default/node_expat.node
 → /usr/lib/node_modules/torrentflix/node_modules/node-expat/compiled/9.4.0/linux/x64/node_expat.node
    at bindings (/usr/lib/node_modules/torrentflix/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/lib/node_modules/torrentflix/node_modules/node-expat/lib/node-expat.js:4:32)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/torrentflix/node_modules/xml2json/lib/xml2json.js:1:75)
```

I tried installing bindings manually with npm, but that didnt work.

**Comment by ItzBlitz98** [comment]
This looks more like an issue with xml2json rather than torrentflix, However https://github.com/dapphub/dapple/issues/125 looks related. 

Try that but replace `deasync.node` with `node_expat.node` with the fix above.

**Comment by bigodel** [comment]
I tried that fix but it didn't work. I was installing it through `npm install -g torrentflix` and so I tried to clone the repo and install it through `sudo npm install` and I get the following messages:

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/joaopedro/Repos/torrentflix/node_modules/node-expat/.node-gyp/8.9.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/joaopedro/Repos/torrentflix/node_modules/node-expat/.node-gyp"
```

**Comment by ItzBlitz98** [comment]
Hm try `sudo npm install --unsafe-perm --verbose -g torrentflix`

**Comment by bigodel** [comment]
Well, for some reason after a lot of `npm remove -g torrentflix` and `sudo npm install --unsafe-perm --verbose -g torrentflix` it finally worked :v 

But I got a little bit curious, why would the `--unsafe-perm` disable the EACCES warning? Could you explain?

**Comment by ItzBlitz98** [comment]
Glad you finally got it working 👍.

Its a long standing issue with node-gyp https://github.com/nodejs/node-gyp/issues/454

**Comment by bigodel** [comment]
Oh, ok, thank you. Will close the issue now, keep up the good work, you've got a wonderful application!
