### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by walidsa3d** [ItzBlitz98/torrentflix#9]
It would be nice to have an option to exit the program or return to the tracker choice list if I don't want to stream any torrent
 "? Torrent to stream (eg. 1, 2, 3..):  "
Besides, I want to see a customized error message when I enter the wrong number/letter (or nothing).

**Comment by ItzBlitz98** [comment]
Agreed navigation is fairly cumbersome and i have done very little error checking something i need to fix, Thanks will get working on that :+1:.

**Comment by ItzBlitz98** [comment]
Added in some better navigation and error checking, If i missed anything feel free to re-open this.

Thanks again :)
