### ISSUE TITLE
Torrentflix froze

### ISSUE THREAD

**Issue by FrankieLaw** [ItzBlitz98/torrentflix#96]
I don't know if this is still being maintained.
I downloaded this for fun and see how it works.

Got through the installation process.
Once I ran **torrentflix** -> **Select torrent site**
The process just froze there.  You cannot ctrl+C out either.

Is this suppose to happen?

**Comment by ItzBlitz98** [comment]
No this isn't supposed to happen, I'm currently looking into it what OS are you using ?

**Comment by FrankieLaw** [comment]
Windows 10 Pro

**Comment by ItzBlitz98** [comment]
I have updated some dependencies that seems to have fixed it for me

**Comment by FrankieLaw** [comment]
It is still persisting on my end. Perhaps I did something incorrect.

![Screenshot (4)](https://user-images.githubusercontent.com/24278524/79669571-719ff600-818a-11ea-9e59-b6eaf271b1ce.png)

**Comment by ItzBlitz98** [comment]
No nothing you are doing i have yet to push a stable release with these changes i will make one soon i have to fix some things first.

Edit:
A new release has been published on here and on npm feel free to update and give it a try.

Thanks for reporting
